In [1]:
import pandas as pd
import numpy as np 
df=pd.read_csv("iris (1).csv") 
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [2]:
x=df[['sepal_length','sepal_width','petal_length','petal_width']] 
y=df[['species']] 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=410)
x_train

,sepal_length,sepal_width,petal_length,petal_width
59,5.2,2.7,3.9,1.4
0,5.1,3.5,1.4,0.2
60,5.0,2.0,3.5,1.0
93,5.0,2.3,3.3,1.0
103,6.3,2.9,5.6,1.8
...,...,...,...,...
134,6.1,2.6,5.6,1.4
145,6.7,3.0,5.2,2.3
140,6.7,3.1,5.6,2.4
37,4.9,3.6,1.4,0.1


In [3]:
x_test

,sepal_length,sepal_width,petal_length,petal_width
57,4.9,2.4,3.3,1.0
10,5.4,3.7,1.5,0.2
1,4.9,3.0,1.4,0.2
124,6.7,3.3,5.7,2.1
112,6.8,3.0,5.5,2.1
86,6.7,3.1,4.7,1.5
2,4.7,3.2,1.3,0.2
131,7.9,3.8,6.4,2.0
15,5.7,4.4,1.5,0.4
79,5.7,2.6,3.5,1.0


In [4]:
x_train

,sepal_length,sepal_width,petal_length,petal_width
59,5.2,2.7,3.9,1.4
0,5.1,3.5,1.4,0.2
60,5.0,2.0,3.5,1.0
93,5.0,2.3,3.3,1.0
103,6.3,2.9,5.6,1.8
...,...,...,...,...
134,6.1,2.6,5.6,1.4
145,6.7,3.0,5.2,2.3
140,6.7,3.1,5.6,2.4
37,4.9,3.6,1.4,0.1


In [5]:
y_test

,species
57,versicolor
10,setosa
1,setosa
124,virginica
112,virginica
86,versicolor
2,setosa
131,virginica
15,setosa
79,versicolor


In [6]:
y_train

,species
59,versicolor
0,setosa
60,versicolor
93,versicolor
103,virginica
...,...
134,virginica
145,virginica
140,virginica
37,setosa


In [9]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)


,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [10]:
y_pred=dtc.predict(x_test) 
y_pred

array(['virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'versicolor',
       'setosa', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor'],
      dtype=object)

In [11]:
from sklearn.metrics import accuracy_score,r2_score,classification_report,confusion_matrix 
acc=accuracy_score(y_test,y_pred) 
print('accuracy_score:',acc) 


accuracy_score: 0.9666666666666667


In [12]:
cm=confusion_matrix(y_test,y_pred)
print('confusion_matrix:\n',cm)
cr=classification_report(y_test,y_pred)
print('classification_report:',cr)

confusion_matrix:
 [[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
classification_report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       1.00      0.91      0.95        11
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

